project:
  title: "How does familiarity impact the computational processes that support face recognition?"
  render:
    - manuscript/manuscript.qmd
    - manuscript/supplementary.qmd
  output-dir: docs
  #site-url: https://rfournier-ncm.github.io/face-familiarity-eam
  #repo-url: https://github.com/rfournier-ncm/face-familiarity-eam
  #archive-url: 
  #preprint-url: 
  
execute:
  cache: false
  freeze: auto
